### PR TITLE
Collin branch

### PR DESCRIPTION
**Pull request by colchapm**
add css grid styling

add createBoard function with test of object.entries method to loop through category questions and post to html

create board template with two category titles and give questions

### CODE REVIEW

**Comment by saoud** [comment]
Looks good to merge to me!

**Review by saoud — APPROVED** [review]
Looks good to merge to me!

**Comment by jessecallahan** [comment]
hey this looks great

**Review by lauriewaller — APPROVED** [review]
Looks great!

**Review by jessecallahan — APPROVED** [review]

**Pull request merged**
