### PR TITLE
Shanen branch

### PR DESCRIPTION
**Pull request by shanencross**
Allowed for generating of arbitrary number of grid elements with JavaScript, so we can have any number of categories. Refactored so that category index and price value for each clue are stored as custom attributes in that clue's html element. Updated UI and CSS styling.

### CODE REVIEW

**Review by colchapm — APPROVED** [review]

**Review by saoud — APPROVED** [review]
Looks good to merge!

**Review by jessecallahan — COMMENTED** [review]
yeah I watched this real time.

**Review by jessecallahan — APPROVED** [review]

**Review by lauriewaller — APPROVED** [review]
Looks good!

**Review by jessecallahan — APPROVED** [review]
my approval granted

**Pull request merged**
